In [1]:
import numpy as np

In [2]:
board=[[7,8,0,4,0,0,1,2,0],
        [6,0,0,0,7,5,0,0,9],
        [0,0,0,6,0,1,0,7,8],
        [0,0,7,0,4,0,2,6,0],
        [0,0,1,0,5,0,9,3,0],
        [9,0,4,0,6,0,0,0,5],
        [0,7,0,3,0,0,0,1,2],
        [1,2,0,0,0,7,4,0,0],
        [0,4,9,2,0,6,0,0,7]]

In [3]:
sudoko = np.array(board).reshape(9,9)

In [4]:
sudoko

array([[7, 8, 0, 4, 0, 0, 1, 2, 0],
       [6, 0, 0, 0, 7, 5, 0, 0, 9],
       [0, 0, 0, 6, 0, 1, 0, 7, 8],
       [0, 0, 7, 0, 4, 0, 2, 6, 0],
       [0, 0, 1, 0, 5, 0, 9, 3, 0],
       [9, 0, 4, 0, 6, 0, 0, 0, 5],
       [0, 7, 0, 3, 0, 0, 0, 1, 2],
       [1, 2, 0, 0, 0, 7, 4, 0, 0],
       [0, 4, 9, 2, 0, 6, 0, 0, 7]])

## Get Column

In [5]:
sudoko[ : , 0]

array([7, 6, 0, 0, 0, 9, 0, 1, 0])

## Get Raw

In [6]:
sudoko[0]

array([7, 8, 0, 4, 0, 0, 1, 2, 0])

In [7]:
2 in sudoko[ : , 3] , 2 in sudoko[6]

(True, True)

# Get subgrid 1

In [8]:
SG1 = sudoko[0:3 , 0:3]

In [9]:
SG1

array([[7, 8, 0],
       [6, 0, 0],
       [0, 0, 0]])

In [10]:
8 in SG1

True

In [11]:
sudoko[2][2]

0

## Dividing Board to 9 subboards (1,4,7 - first raw)

In [12]:
def idGrid(x,y, num):
    if x in [0,1,2] and y in [0,1,2]: 
        return num in sudoko[0: 3, 0: 3]
    if x in [3,4,5] and y in [0,1,2]: 
        return num in sudoko[3: 6, 0: 3]
    if x in [6,7,8] and y in [0,1,2]:
        return num in sudoko[6: 9, 0: 3]
    if x in [0,1,2] and y in [3,4,5]:
        return num in sudoko[0: 3, 3: 6]
    if x in [3,4,5] and y in [3,4,5]:
        return num in sudoko[3: 6, 3: 6]
    if x in [6,7,8] and y in [3,4,5]:
        return num in sudoko[6: 9, 3: 6]
    if x in [0,1,2] and y in [6,7,8]:
        return num in sudoko[0: 3, 6: 9]
    if x in [3,4,5] and y in [6,7,8]:
        return num in sudoko[3: 6, 6: 9]
    if x in [6,7,8] and y in [6,7,8]:
        return num in sudoko[6: 9, 6: 9]
   

In [13]:
idGrid(2, 7, 3)

False

## Function to get the "0" => Valid/ Empty slots that needs filing

In [14]:
def isZero():
    return [[x, y] for x in range(9) for y in range(9) if sudoko[x][y] == 0]

In [15]:
#isZero()

## Function to state whether a guess is possible or not

In [16]:
def validGuess(x,y,gs):
    if gs in sudoko[x]:
        return False
    if gs in sudoko[ : ,y]:
        return False
    if idGrid(x,y,gs):
        return False
    return True

In [17]:
#validGuess(7 , 7, 4)

## Funcation to solve the Sudoku using BackTrack

In [27]:
def solveSudoku():
    if len(isZero()) == 0:
        print(sudoko)
        print("done")
        break 
        
#     if isZero() == []:
#         print("No Zeros!")
#         print(isZero())
#         return False
    
    empty_slot = isZero()[0]
    
    for k in range(1,10):
        if validGuess(empty_slot[0], empty_slot[1], k):
            print(isZero()[0])
            sudoko[empty_slot[0]][empty_slot[1]] = k
            print(sudoko)
            print("\n")
            solveSudoku()
            sudoko[empty_slot[0]][empty_slot[1]] = 0
            
    return
                   
       
    

SyntaxError: 'break' outside loop (<ipython-input-27-54c7a3842e8b>, line 8)

In [28]:
solveSudoku()

[0, 2]
[[7 8 3 4 0 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


[0, 4]
[[7 8 3 4 9 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


[0, 2]
[[7 8 5 4 0 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


[0, 4]
[[7 8 5 4 3 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


[0, 5]
[[7 8 5 4 3 9 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


[0, 8

In [20]:
len(isZero())

43